#!/usr/bin/env python3
"""
Convert a PNG image to an RGB565 C header for ESP32 TFT_eSPI.
Fits the image to 240x240 (the Freenove round LCD resolution).
Output: logo.h in the firmware/src/ directory.
"""

import sys
from pathlib import Path
from PIL import Image

TARGET_W = 240
TARGET_H = 240


def rgb888_to_rgb565(r, g, b):
    """Convert 8-bit RGB to 16-bit RGB565 (big-endian as stored by TFT_eSPI)."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b & 0xF8) >> 3)


def convert(image_path: Path, out_path: Path):
    img = Image.open(image_path).convert("RGBA")

    # Fit to target size while keeping aspect ratio (letterbox on black)
    img.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)

    # Center on black canvas
    canvas = Image.new("RGBA", (TARGET_W, TARGET_H), (0, 0, 0, 255))
    offset_x = (TARGET_W - img.width) // 2
    offset_y = (TARGET_H - img.height) // 2
    canvas.paste(img, (offset_x, offset_y), img)

    # Convert to RGB and generate RGB565 array
    rgb_img = canvas.convert("RGB")
    pixels = list(rgb_img.getdata())

    rgb565_data = [rgb888_to_rgb565(r, g, b) for r, g, b in pixels]

    # Write C header
    with open(out_path, "w") as f:
        f.write("// Auto-generated by convert_logo.py\n")
        f.write("// Source: {}\n".format(image_path.name))
        f.write("// Format: RGB565, {}x{}\n".format(TARGET_W, TARGET_H))
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define LOGO_WIDTH  {}\n".format(TARGET_W))
        f.write("#define LOGO_HEIGHT {}\n".format(TARGET_H))
        f.write("\n")
        f.write("const uint16_t logo_bitmap[{}] PROGMEM = {{\n".format(len(rgb565_data)))

        # Write 16 values per line for readability
        for i in range(0, len(rgb565_data), 16):
            line_vals = rgb565_data[i : i + 16]
            hex_vals = ["0x{:04X}".format(v) for v in line_vals]
            f.write("    " + ", ".join(hex_vals))
            if i + 16 < len(rgb565_data):
                f.write(",")
            f.write("\n")

        f.write("};\n")

    print(f"[OK] Generated {out_path}")
    print(f"     Dimensions: {TARGET_W}x{TARGET_H}, {len(rgb565_data)} pixels")


if __name__ == "__main__":
    repo_root = Path(__file__).resolve().parent.parent.parent
    logo_png = repo_root / "frontend" / "assets" / "logo.png"
    out_h = repo_root / "firmware" / "src" / "logo.h"

    if not logo_png.exists():
        print(f"[ERROR] Logo not found: {logo_png}")
        sys.exit(1)

    out_h.parent.mkdir(parents=True, exist_ok=True)
    convert(logo_png, out_h)
